name: song_intro_duel
description: MVP Flutter para adivinar canciones con Deezer previews y salas de 2 jugadores usando Firebase.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.0
  cloud_firestore: ^5.6.9
  just_audio: ^0.9.46
  http: ^1.2.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
