// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfEP-b5BdTk_kaS1k2TZnqJ58tTMqIBtE',
    appId: '1:1067200534218:web:53c486e45ee3c67c48c633',
    messagingSenderId: '1067200534218',
    projectId: 'song-intro-duel',
    authDomain: 'song-intro-duel.firebaseapp.com',
    storageBucket: 'song-intro-duel.firebasestorage.app',
    measurementId: 'G-ZY045C0P7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChoGgqwuMJ8IEpskFbs821KcL250cLlqk',
    appId: '1:1067200534218:android:1178fb13af4f8c9448c633',
    messagingSenderId: '1067200534218',
    projectId: 'song-intro-duel',
    storageBucket: 'song-intro-duel.firebasestorage.app',
  );
}
